import turtle

WIDTH = 800
HEIGHT = 400
scr = turtle.Screen ()
scr.setup (WIDTH, HEIGHT)
# scr.tracer(0)

t = turtle.Turtle()

def left_cross (x, y, w, h, colour = 'green', angle = 0):
    t.setheading(0)
    t.color(colour)
    t.fillcolor(colour)
    
    t.left(angle)
    t.begin_fill()
    t.pu()
    t.goto(x,y)
    t.pd()
    t.forward(w)
    t.right(90)
    t.forward(h/2)
    t.left(90)
    t.forward(w*2)
    t.right(90)
    t.forward(w)
    t.right(90)
    t.forward(w*2)
    t.left(90)
    t.fd(h)
    t.right(90)
    t.fd(w)
    t.right(90)
    t.fd(h)
    t.left(90)
    t.forward(w*2)
    t.right(90)
    t.fd(w)
    t.right(90)
    t.forward(w*2)
    t.left(90)
    t.fd(h/2)
    t.end_fill()

def right_cross (x, y, w, h, colour = 'green', angle = 0):
    t.setheading(0)
    t.color(colour)
    t.fillcolor(colour)

    
    t.right(angle)
    t.begin_fill()
    t.pu()
    t.goto(x,y)
    t.pd()
    t.forward(w)
    t.right(90)
    t.forward(h/2)
    t.left(90)
    t.forward(w*2)
    t.right(90)
    t.forward(w)
    t.right(90)
    t.forward(w*2)
    t.left(90)
    t.fd(h)
    t.right(90)
    t.fd(w)
    t.right(90)
    t.fd(h)
    t.left(90)
    t.forward(w*2)
    t.right(90)
    t.fd(w)
    t.right(90)
    t.forward(w*2)
    t.left(90)
    t.fd(h/2)
    t.end_fill()



right_cross(100, 5, 15, 75, 'dark grey', 0)
right_cross(0, 0, 50, 250, 'black', 10)
left_cross(250, 50, 25, 125, 'grey', 5)
# scr.update()
turtle.done()